- src/ipython_clojure/core.clj
There shouldn't be a message on the iopub socket called `execute-content`...it should be `execute_input`, see here:
https://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-iopub-pub-sub-channel
My editor also fixed some trailing whitespace
> Fix execute-content -> execute_input

- bin/clojupyter.template
> Add template file back to repository

- README.md
Introduce how to install on windows
> Add section "Installation on Windows" to README.md

- src/clojupyter/core.clj
- test/clojupyter/core_test.clj
The first fix for stdout broke stderr. Ugh!
> fixed stdout and stderr not printing

- project.clj
- src/clojupyter/misc/zmq_comm.clj
- test/clojupyter/core_test.clj
> added support for utf-8

- project.clj
- src/clojupyter/core.clj
- src/clojupyter/misc/history.clj
- src/clojupyter/misc/messages.clj
- src/clojupyter/misc/states.clj
- test/clojupyter/misc/history_test.clj
Implements history_request for Jupyter
History will be preserved across sessions and save in a sqlite database.
> History request

- README.md
> Fix notebook link in readme

- doc/usage-scenarios.md
> spell correct:

- doc/conda-installing.md
Added some additional documentation to clarify how to use Conda Environments with Clojupyter
> Conda Environment documentation

- examples/demo-clojupyter.ipynb
"buy Jupyter" -> "by Jupyter" in line 148
> Correct minor misspelling

- build.clj
- deps.edn
- doc/dev.md
- resources/clojupyter/assets/version.edn
- update deps with maven-supported coordinates
- create build command for generating pom file
- create support for clojars deployment
> 4.x: Prep for release and clojars deploy

- src/clojupyter/install/local_actions.clj
- src/clojupyter/kernel/handle_event/inspect.clj
https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernelspecs
> fix empty inspect and windows install dirs

- deps.edn
- resources/clojupyter/assets/version.edn
- src/clojupyter/zmq_util.clj
Fixes bug logged here https://github.com/zeromq/jeromq/issues/994#issuecomment-2258087903
This bug prevented us from upgrading to version 5.3+ of jeromq.
Cutting release on this PR branch
> Upgrade zmq lib and fix incorrect API usage for shadows

- deps.edn
- src/clojupyter/install/conda/yaml.clj
added clj-commons/clj-yaml to deps
fixes #183
> use clj-yaml

- build.clj
- deps.edn
- test/clojupyter/run_tests.clj
- **build: more control of versioning**
- **Fix proper exit code for tests**
> fix test exit

- README.md
- doc/usage-scenarios.md
As a hobbyist immersed in data analysis, it took people's time on Zulip chat and some code inspection to learn me that Clojupyter indeed has the best beginner experience out there (since Clojure ceased to be just a Java library). I think it is important to describe and show this in a prominent place in README.md.
> In Readme.md, mention the pre-built release-uberjar and "eval" option

- Changelog.md
just to give you the links, in case you want to mention kindly compatibility for next release
> refer to kindly and compatibility table

- examples/kind-compatibility.ipynb
- src/clojupyter/misc/kind.clj
- test/clojupyter/misc/kind_test.clj
> get kind/table with dataset working

- deps.edn
> Update markdown dep> Fix #218

- deps.edn
- examples/kind-compatibility.ipynb
- src/clojupyter/misc/kind.clj
- test/clojupyter/misc/kind_test.clj
disabled option checking for now.
Need to go back to it and implement option handling
> fixes #222

- deps.edn
- src/clojupyter/misc/kind.clj
- test/clojupyter/misc/kind_test.clj
cleaned other kind dependencies
> use KindlyRender0.1.5-alpha
