.gitignore, src/ipython_clojure/core.clj
Clojupyter was not correctly handling the shell socket, which is a ZMQ router socket. With router sockets, you have to read and send back the ZMQ identifiers. For some weird reason the code was sending back the IPython session ID instead of these identifiers. As a result, ZMQ was silently dropping any responses on the shell socket so the frontend never saw them. This PR fixes this problem and also makes Clojupyter gracefully handle an empty key.
=> Fix router socket handling

src/ipython_clojure/core.clj
Currently, clojupyter will choke if any of the code it's running throws an exception. This makes it catch the exception and send appropriate Jupyter messages.
=> Catch errors

Makefile, README.md
Instead of having `make` take care of installation as well as the initial project build, this new Makefile is separated into two major parts for installation
1. Project build
2. Kernel installation
Each operation is side-effect free and disjoint from the other operations. This method of separation is somewhat standard among projects that need to be built, and it would be good to keep with that. Anyone initially downloading the project will expect this separation.
=> Makefile Standardization

src/ipython_clojure/core.clj
This prevents exceptions where lists get interpreted incorrectly as expressions.
Before:
After:
=> Avoid exceptions when return value is a list

README.md, project.clj, resources/connect.json, src/ipython_clojure/core.clj, src/ipython_clojure/middleware/pprint.clj, src/ipython_clojure/middleware/stacktrace.clj, test/core_test.clj
As the subject suggests, this is a major change. Writing a reliable REPL, which is where this code seemed to be heading, is a lot of work. tools.nrepl is a REPL solution made just for this sort of problem, and it is tested (used by emacs/cider etc.) and solid. See the section [why nREPL?](https://github.com/clojure/tools.nrepl) at tools.nrepl github.
I have not experienced any problems changing namespaces in this fork. I implemented stacktraces using code from cider-nrepl.
=> use nrepl, not eval

src/clojupyter/core.clj
This works for the browser client. Oddly, the first time printing (e.g. (print "hello")) using the jupyter-console, stdout goes to the cider buffer; thereafter it works fine.
=> fix stdout not printing

Makefile, README.md, resources/kernel.json
Modified location of the install assets to match with the official jupyter documentation
http://jupyter-client.readthedocs.io/en/latest/kernels.html.
=> Changed location of the installation assets.

.gitignore, project.clj, src/clojupyter/core.clj, src/clojupyter/middleware/mime_values.clj, src/clojupyter/misc/helper.clj
I have cleaned up the dependencies and removed the "SNAPSHOT" from the version number.  I would like the package to be published to [clojars](https://clojars.org/) to allow [lein-jupyter](https://github.com/didiercrunch/lein-jupyter) to be self contained and published to clojar itself.
many thanks again for this awesome kernel.
=> Cleaned up dependencies and release version 0.1.0.

src/clojupyter/protocol/mime_convertible.clj, test/clojupyter/protocol/mime_convertible_test.clj
Current head will show `clojure.lang.LazySeq@...` for expressions which yield lazy sequences (see issue #39). This PR fixes the issue by replacing `str` on the transport result with `pr`. The down side here is if someone makes an expression that yields too large a value, we'll render all of it. This is however consistent with Jupyter in general where you can shoot yourself in the foot with rendering a result. 
/cc @yanoyan who reminded me this was a bug
=> Fix lazy sequences

src/clojupyter/core.clj
Stack trace is broken in master
Looks like the middleware was not loaded properly.
This change fixes it. The unit test currently do not catch this error, I think we might want to add a test for this in the future.
=> Fix stacktrace middleware

project.clj
pomegranate was pulling in an old version of httpclient which was
causing compilation erros when using [clj-http][]. This commit bumps
pomegranate to the latest stable release.
[clj-http]: https://github.com/dakrone/clj-http
=> Update pomegranate version

src/clojupyter/core.clj, src/clojupyter/misc/messages.clj, src/clojupyter/misc/nrepl_comm.clj, src/clojupyter/misc/tokenize.clj, src/clojupyter/protocol/nrepl_comm.clj
Shift-Tab sends an inspect_request to the kernel.
This brings up a tooltip with the function/macro/namespace docstring.
=> Support inspect_request

README.md
Using `jupyter-console --kernel=clojupyter` leads to `jupyter_client.kernelspec.NoSuchKernel: No such kernel named clojupyter`
=> Fix the kernel name in the jupyter-console command

src/clojupyter/util_actions.clj
This breaks packaging on nixos because /usr/bin isn't a thing.
=> fix: Use /usr/bin/env which

deps.edn, src/clojupyter/messages.clj, src/clojupyter/util.clj, src/clojupyter/util_actions.clj
Fixes #134 by not depending on first parsing the message body and then signing the re-serialized body. As mentioned in #134 this depends on identical map->json serialization in the kernel and the jupyter lab frontend (which broke/changed in the most recent version of jupyter lab - and maybe all versions 3.x).
This PR
- changes the parameters to the signer to be a seq of strings rather than a seq of maps; this enables us to check the signature of the message without depending on fully parsing the message body
In addition, we upgrade some quite old dependencies, and fix a bad invocation of `(sh/sh "/usr/bin/env which" exe)` to `(sh/sh "/usr/bin/env" "which" exe)` (which may fail in some cases).
=> Fix signing in lab 3.x & update some quite old deps

deps.edn, project.clj, resources/clojupyter/assets/version.edn, src/clojupyter/kernel/handle_event/comm_msg.clj, src/clojupyter/kernel/handle_event_process.clj, src/clojupyter/log.clj, src/clojupyter/messages.clj
This PR updates all deps to better support 1.11.1 (note that not all deps have 1.11.1 support so there is future work here)
- Fix-up bad handling of comms_open with widgets
- Bump protocol to 5.3 (no handling of Kernel interrupt but also not needed)
- This also supports Mac M1 (tested with reasonably new jupyter* and Mac M1 Max)
Closing #163 #162 #160 #159 #146 #142 
Note for Conda users: right now the only supported installation path is via clojars or via building locally. At the moment, I don't have the knowledge or bandwidth to support installation of clojupyter via conda.
=> Clojure 1.11.1 and support latest lab

src/clojupyter/install/conda/yaml.clj
It seems like the`BUILD-DEPS` requiring `openjdk=8` and `maven` for conda are a bit dated.
`maven` would probably be implicit from `lein` being the builder anyway.
So .. loosening the `BUILD-DEPS` to just `openjdk` allows for the following to succeed
export BUILDNUM=2
make conda-build
lein clojupyter install
..which allows the start of `jupyter notebook` both from the command line and from Anaconda.
=> bump openjdk version to the latest and remove maven requirement

build.clj, deps.edn, resources/clojupyter/assets/version.edn
Supersedes: https://github.com/clojupyter/clojupyter/pull/176 which updates dependencies and bumps to version 0.4.326
- **Update deps.edn**
- **Deps: bump all versions**
- **Bump: clojupyter version**
=> Updating deps and releasing

deps.edn
this fixes the errors i'm getting for
```
Caused by: clojure.lang.ArityException: Wrong number of args (12) passed to: taoensso.timbre/-log!
at clojure.lang.AFn.throwArity(AFn.java:429)
at clojure.lang.AFn.invoke(AFn.java:82)
```
I tried excluding timbre and manually installing this version timbre but kept running into
```
Caused by: Syntax error macroexpanding taoensso.encore/defalias at (taoensso/encore.cljc:711:6).
[encore/defalias] Failed to resolve source var for sym: taoensso.truss/with-data
```
=> Update timbre dep

build.clj, deps.edn, src/clojupyter/util.clj
its a follow-up change from #190 
To work from a devcontainer either requires this change
or to install certain xwindows libraries in the devcontainer.
Boht are valid options and should have no impact on clojupyter behavoiur.
Please decide what you prefer
=> support headless
